spring:
  servlet:
    #文件大小限制
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    default:
      name: hxdb
      url: jdbc:mysql://192.168.0.37:3306/sxcx?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
      username: root
      password: huaxin@87775236
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  session:
    store-type: none

#fastDFS
fdfs:
  conf: ./fdfs_client.conf
  soTimeout: 1501
  connectTimeout: 601
  thumbImage: #缩略图
    width: 150
    height: 150
  trackerList:
    - 192.168.0.30:22122
http:
  uploadIp : http://192.168.0.30:8888

temp_upload_url: ./upload

water_mark:
  content: 城乡供水绩效评估
  font_size: 50
  font_color:
    r: 225
    g: 225
    b: 225

uploadFile:
  maxFileSize: 1024
  imageType: jpg|jpeg|png
  fileType: docx|doc|pdf|ppt|pptx|txt|xls|xlsx|mp4|avi|wmv|rmvb|rm|flv|mov|jpg|jpeg|png|rar|zip|mp3
  docType: docx
  xlsType: xlsx


file :
  staticAccessPath : /upload/**
  #文件上传目录
  uploadFolder : /usr/local/attachment/xz
  #文件访问路径
  urlPath: /upload/
  imageUrlPath: /upload/image
  attachmentUrlPath: /upload/attachment
  contractUrlPath: /upload/xz
  imagePath: /usr/local/attachment/xz/image
  attachmentPath: /usr/local/attachment/xz/attachment


ftp:
  host: 192.168.2.124 # linux服务器IP
  port: 22
  username: root
  password: huaxin12
  baseUrl: /home/application/sczc
  uploadDir: /upload #nginx 映射路径
  nginxUrl: http://27.17.43.146:48899 # 前端访问连接  外网nginx 映射地址


